### ISSUE TITLE
Bad resolution

### ISSUE THREAD

**Issue by MeblIkea** [lfelipe1501/Atomic-GRUB2-Theme#9]
Hi, my screen is 1920x1080. How do I set the grub to my resolution please? Thanks.

**Comment by Ghoelian** [comment]
This isn't related to any theme, you have to edit ``/etc/default/grub`` (at least that's what it is in Debian, not sure about other distro's), and change/uncomment/add ``GRUB_GFXMODE=1920x1080``, or whatever resolution you want. Then you have to update grub of course: ``sudo update-grub``.

**Comment by MeblIkea** [comment]
I didn't test, but thanks, I will test it when my computer will work again
